// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

//현재의 플렛폼에 따라 옵션을 변환한다.
//web, android, ios에 대해서는 기능하며, macOS, windows, linux에서는 기능하지 않도록 한다.
//담당: 이재인

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpNwegVz4c3urD_sGc-NR3sXjyosphBlQ',
    appId: '1:906096207491:web:c419dfd79170bace3d1db6',
    messagingSenderId: '906096207491',
    projectId: 'chac-k',
    authDomain: 'chac-k.firebaseapp.com',
    storageBucket: 'chac-k.appspot.com',
    measurementId: 'G-R4YWXKZEVN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlbvfvCqlu2skPVtEbteEeACpmC6sBYZI',
    appId: '1:906096207491:android:a7807595738679b83d1db6',
    messagingSenderId: '906096207491',
    projectId: 'chac-k',
    storageBucket: 'chac-k.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBttuL82x73XIlPO6IgDmU9mtMHTw75bwU',
    appId: '1:906096207491:ios:232c0845fd23d8b63d1db6',
    messagingSenderId: '906096207491',
    projectId: 'chac-k',
    storageBucket: 'chac-k.appspot.com',
    iosBundleId: 'com.example.bookJuk',
  );
}
